import type { Metadata } from "next";
import "./globals.css";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";

export const metadata: Metadata = {
  title: "SIS E-BOTO 2025",
  description: "Generated by EVEREST",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      {/* Tip: gamita either .className or .variable (or both) */}
      <body className={`${GeistSans.className} ${GeistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
